### PR TITLE
Changes to 'config/index.js', 'http/index.js', 'database/index.js', '…

### PR DESCRIPTION
**Pull request by cags84**
…api/index.js' files.

- Add new variable to .env 'HTTP_HOST', define the ip address to server, default is 127.0.0.1.
- Modify 'config/index.js' file, the 'host' property was added in the http object.
- Modify 'http/index.js' file, because async/await is used, used try/catch.
- Deleted /* eslint-disable no-console */, /* eslint-enable no-console */, fix .eslintrc
- Updated accessLogDir into 'api/index.js', added '../logs/' to the path.
- Other minnor chanches.

### CODE REVIEW

**Comment by cags84** [comment]
If this pull request applies, don't forget to change the variable in the .env file:

Before:

````sh
LOG_ACCESS=../logs/access.log
````

After:

````sh
LOG_ACCESS=access.log
````

**Comment by cags84** [comment]
Updated .gitignore file.

**Comment by cags84** [comment]
Add .editorconfig and .eslintignore files, according to: 
- [.eslintignore](https://eslint.org/docs/user-guide/configuring/ignoring-code)
- [.editorconfig](https://editorconfig.org/)

**Review by jestrade — APPROVED** [review]
LGTM

**Comment by cags84** [comment]
Updated

**Pull request merged**
